#@data/values
---
concourse_release_branch: release/6.7.x
deployments_uri: git@github.com:concourse/platform-automation-deployments.git
deployments_branch: master
deployments:
- iaas: gcp
  opsman_glob: "*gcp*.yml"
  stemcell_glob: "light*google*.tgz"
  tags: []
